### ISSUE TITLE
Improve computational efficiency for OscTrackingData

### ISSUE THREAD

**Issue by yminchen** [DAIRLab/dairlib#139]
To increase computation speed, we should combine 
&nbsp;&nbsp;&nbsp;&nbsp; `UpdateYAndError`
&nbsp;&nbsp;&nbsp;&nbsp; `UpdateYdotAndError`
&nbsp;&nbsp;&nbsp;&nbsp; `UpdateYddotDes`
&nbsp;&nbsp;&nbsp;&nbsp; `UpdateJ`
&nbsp;&nbsp;&nbsp;&nbsp; `UpdateJdotV`
into one single method.

As an example, Jacobian is computed twice in `UpdateYdotAndError` and `UpdateJ`

**Comment by yangwill** [comment]
I also originally thought that we could share the Jacobian call between those two methods but upon further inspection UpdateJ uses plant_wo_spr and UpdateYdotAndError uses plant_w_spr

**Comment by yminchen** [comment]
You are right! That's probably why I didn't merge those two together before
