### ISSUE TITLE
Cassie state estimator

### ISSUE THREAD

**Issue by mposa** [DAIRLab/dairlib#28]
Create a state estimator for Cassie. First three priorities are

1. Solve kinematic loop closure for unobserved joint positions and velocities
2. Calculate ground reaction forces
3. Combine kinematic and inertial data to estimate pelvis position and velocity

**Comment by yminchen** [comment]
> 

Didn't do a good job tracking progress here, but the TODO list has been completed for a while. @mposa We can probably close this issue
