### ISSUE TITLE
where is "convex_plane_decomposition_msgs/PlanarTerrain.h"

### ISSUE THREAD

**Issue by ytwboxing** [DAIRLab/dairlib#364]
hello, Brian Acosta, thanks for sharing your excellent work， I cannot found  
"convex_plane_decomposition_msgs/PlanarTerrain.h" and "convex_plane_decomposition_msgs/Polygon2d.h", could you please tell me the folder of these files, or how to gen them. thank u!

**Comment by Brian-Acosta** [comment]
Sorry for the poor documentation, all of the perceptive locomotion work is still undergoing development. Those headers are from the [elevation_mapping_cupy](https://github.com/leggedrobotics/elevation_mapping_cupy) package. To use them, build `elevation_mapping_cupy` inside a ros noetic workspace, then set the environment variable LOCAL_ROS_INSTALL_PATH to the path to the devel folder of your ros workspace. Bazel should then be able to find those headers as part of the @ros_local package, if they are needed.
