### ISSUE TITLE
The output of Cassie state estimator is stale

### ISSUE THREAD

**Issue by yminchen** [DAIRLab/dairlib#63]
In `cassie-state-estimator` branch. Commit # `1fc510af1c9625aa555a2a9698089c7d6da69f1f`

The output of `CassieRbtStateEstimator` (a child of `LeafSystem`) is not computed from the latest Lcm message, but from the previous one. 

It seems that the per-step update `CassieRbtStateEstimator::Update()` is not called before the output function `CassieRbtStateEstimator::CopyStateOut()`. 
Experiment: We stored `context.time` into a discrete state of `CassieRbtStateEstimator` in `Update()`, and printed the following two things in `CopyStateOut()` 
- `context.time` and 
- the time stored as a discrete state.

Result: `context.time` is always bigger than the time stored as a discrete state.

Procedures to reproduce the experiment result:
- Build `examples/Cassie:dispatcher_robot_out` and `examples/Cassie:run_simple_sim`.
- In procman, run `2.a.dispatcher-robot-out (drake)` and then `1.simulator (dispatched)`.
- Look at the message printed by `dispatcher_robot_out`.

**Comment by yminchen** [comment]
It turned out that `context.time` lags behind `lcm.time`, so we cannot use `context.time` to determine whether we should run the update step of EKF or not.

**Comment by yminchen** [comment]
One way to fix this is to add an extra output port that only passes `lcm.time`, so `StateEstimator` has access to `lcm.time`. 

However, we will ignore the issue for now, since TRI people is modifying `LcmDrivenLoop`.

**Comment by yminchen** [comment]
Found the reason why context.time lags behind lcm.time. 

Drake documentation (Class `Simulator` and Section **How the simulation is stepped**) shows the pseudocode that does the discrete update. The code is
    `xd⁺(tₛ) ← DoAnyDiscreteUpdates(tₛ, x*(tₛ))`
where `tₛ` is the start time of the step.  
Since they feed `tₛ` into the update function, we don't get the end time from `context.time`.

**Comment by mposa** [comment]
Per conversation with Evan and Russ on slack, two possible approaches are suggested.

1. When a new message is received, and before the simulator is advanced, register a new `kTimed` event at `t=lcm.time`. The event handler would be the EKF update.
2. Alternatively, declare the EKF update event as a `ForcedEvent` (using `DeclareForcedDiscreteUpdateEvent`). After advancing the simulation, call `CalcDiscreteVariableUpdates`.

Option 1 requires, in the loop, declaring events at a particular time for the EKF and any system with similar requirements. 

Option 2 uses a more general event framework, and the in-loop function call is much simpler. The downside of (2) are that (a) the `ForcedEvent` will be triggered by other actions (like publish calls), and so may be triggered more than once per step, and (b) that the call to `CalcDiscreteVariableUpdates` may unnecessarily trigger events in other systems.

Either approach will work.  (1) is the same workflow that `LcmSubscriberSystem` uses, and creates less overhead. (2) offers more user control, but is a little more complex.

**Comment by mposa** [comment]
@yangwill @yminchen Does this issue relate to the measured delay in the system? Assuming this issue is still true, we have an extra `T` of delay which could be fixed by addressing this.

**Comment by yminchen** [comment]
@mposa The context time delay `T` here shouldn't contribute to the measured torque delay, because both commanded and measured torque were shifted by `T`

For what it's worth, the context time delay `T` in the experiment should be 1 ms because, I think, the UDP message publish rate is 1kHz

**Comment by yminchen** [comment]
@mposa I just added PR #187 to fix this issue
