### ISSUE TITLE
Visualize a motion within one figure

### ISSUE THREAD

**Issue by yminchen** [DAIRLab/dairlib#98]
Use case: if we want to present a robot motion (e.g. walking gait) in a figure of a paper, one way is to pick a few key frames and overlap them together. 

Not sure whether we can prevent Drake visualizer from erasing the previous image. If so, overlapping the key frames should be easy. 

Another solution: 
Let's say we have 20 key frames. We create 20 robots in a single `MultibodyPlant`. Assign the positions to these robots, and draw.

**Comment by mposa** [comment]
This is superseded by #103
