### ISSUE TITLE
How to use precompiled libsnopt.so in dairlib ?

### ISSUE THREAD

**Issue by JunLi-HIT** [DAIRLab/dairlib#99]
I would like to use snopt. I have got a student version license of it and lib files( .so, .a ).
However, the way dairlib provides to set the path for snopt in the README.md is 
export SNOPT_PATH=<the directory you downloaded to>/snopt7.6.tar.gz .

How to use snopt in dairlib in case of having snopt7.lic, libsnopt7_cpp.a, and libsnopt7_cpp.so files ? Or could you update the Complete Build Instructions in README.md ?

**Comment by mposa** [comment]
Great question--unfortunately, I'm not sure whether or not the student version is compatible. We are mimicking Drake's use of snopt. From a quick search over there, it looks as if this may not be possible: https://github.com/RobotLocomotion/drake/issues/8836

For what it's worth, SNOPT is not strictly required. While we use it for our trajectory optimization, it would be fairly easy to remove all SNOPT-specific calls and instead use something open source, like IPOPT.

**Comment by JunLi-HIT** [comment]
Thank you so much for your guide.
